### ISSUE TITLE
Why minSdkVersion 19?

### ISSUE THREAD

**Issue by stephenruda** [pzienowicz/androidx-auto-scroll-view-pager#2]
The original auto-scroll-view-pager by Trinea had a `minSdkVersion 8`.  I was just curious if it is possible to update this library to support older versions of android?  It is currently set to `mindSdkVersion 19`.

My project uses `mindSdkVersion 15`.  I forked the library and set the minSdkVersion to 15 myself and everything is working fine.

Thanks!

**Comment by pzienowicz** [comment]
Sorry for long reaction ;) Version 1.2.0 supports now minSdkVersion = 15. 
Tested on real device (it was hard to find it) and works correctly.
