### ISSUE TITLE
How to Set Separate Slider Time for Each Item

### ISSUE THREAD

**Issue by laxmanvision** [pzienowicz/androidx-auto-scroll-view-pager#8]
For example, some items should display for 3 seconds, while others should display for 5 seconds. How can I implement this functionality effectively? Are there any best practices or examples to handle this use case?

**Comment by pzienowicz** [comment]
You need to improve the code and pass not the list of images, but the list of pairs, where each pair is the image and the time that image should be displayed. Feel free to contribute ;)

**Comment by laxmanvision** [comment]
> You need to improve the code and pass not the list of images, but the list of pairs, where each pair is the image and the time that image should be displayed. Feel free to contribute ;)

Thank you
